"use strict";
var menuDisplayed = false;
var clockDisplayed = true;
var linksDisplayed = true;
var linksValue = "111111";
var isMouseInLinksMenu = false;
var isMusicPlaying = false;
var volume = 0;
var isVolumeMuted = true;
var isMouseInVolumeMenu = false;
var music = new Audio("assets/music/osc_ambient_time_1-8.mp3");
